//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace COS.Application.Shared
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RONEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RONEntities object using the connection string found in the 'RONEntities' section of the application configuration file.
        /// </summary>
        public RONEntities() : base("name=RONEntities", "RONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RONEntities object.
        /// </summary>
        public RONEntities(string connectionString) : base(connectionString, "RONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RONEntities object.
        /// </summary>
        public RONEntities(EntityConnection connection) : base(connection, "RONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RonEmployee> RonEmployees
        {
            get
            {
                if ((_RonEmployees == null))
                {
                    _RonEmployees = base.CreateObjectSet<RonEmployee>("RonEmployees");
                }
                return _RonEmployees;
            }
        }
        private ObjectSet<RonEmployee> _RonEmployees;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RonEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRonEmployees(RonEmployee ronEmployee)
        {
            base.AddObject("RonEmployees", ronEmployee);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RONModel", Name="RonEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RonEmployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RonEmployee object.
        /// </summary>
        /// <param name="hR_ID">Initial value of the HR_ID property.</param>
        /// <param name="surname">Initial value of the Surname property.</param>
        public static RonEmployee CreateRonEmployee(global::System.String hR_ID, global::System.String surname)
        {
            RonEmployee ronEmployee = new RonEmployee();
            ronEmployee.HR_ID = hR_ID;
            ronEmployee.Surname = surname;
            return ronEmployee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HR_ID
        {
            get
            {
                return _HR_ID;
            }
            set
            {
                if (_HR_ID != value)
                {
                    OnHR_IDChanging(value);
                    ReportPropertyChanging("HR_ID");
                    _HR_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("HR_ID");
                    OnHR_IDChanged();
                }
            }
        }
        private global::System.String _HR_ID;
        partial void OnHR_IDChanging(global::System.String value);
        partial void OnHR_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                if (_Surname != value)
                {
                    OnSurnameChanging(value);
                    ReportPropertyChanging("Surname");
                    _Surname = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Surname");
                    OnSurnameChanged();
                }
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                OnHireDateChanging(value);
                ReportPropertyChanging("HireDate");
                _HireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HireDate");
                OnHireDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _HireDate;
        partial void OnHireDateChanging(Nullable<global::System.DateTime> value);
        partial void OnHireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkGroup
        {
            get
            {
                return _WorkGroup;
            }
            set
            {
                OnWorkGroupChanging(value);
                ReportPropertyChanging("WorkGroup");
                _WorkGroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WorkGroup");
                OnWorkGroupChanged();
            }
        }
        private global::System.String _WorkGroup;
        partial void OnWorkGroupChanging(global::System.String value);
        partial void OnWorkGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CostCenter
        {
            get
            {
                return _CostCenter;
            }
            set
            {
                OnCostCenterChanging(value);
                ReportPropertyChanging("CostCenter");
                _CostCenter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CostCenter");
                OnCostCenterChanged();
            }
        }
        private global::System.String _CostCenter;
        partial void OnCostCenterChanging(global::System.String value);
        partial void OnCostCenterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Division
        {
            get
            {
                return _Division;
            }
            set
            {
                OnDivisionChanging(value);
                ReportPropertyChanging("Division");
                _Division = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Division");
                OnDivisionChanged();
            }
        }
        private global::System.String _Division;
        partial void OnDivisionChanging(global::System.String value);
        partial void OnDivisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalaryGroup
        {
            get
            {
                return _SalaryGroup;
            }
            set
            {
                OnSalaryGroupChanging(value);
                ReportPropertyChanging("SalaryGroup");
                _SalaryGroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SalaryGroup");
                OnSalaryGroupChanged();
            }
        }
        private global::System.String _SalaryGroup;
        partial void OnSalaryGroupChanging(global::System.String value);
        partial void OnSalaryGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LeaveDate
        {
            get
            {
                return _LeaveDate;
            }
            set
            {
                OnLeaveDateChanging(value);
                ReportPropertyChanging("LeaveDate");
                _LeaveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeaveDate");
                OnLeaveDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LeaveDate;
        partial void OnLeaveDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLeaveDateChanged();

        #endregion
    
    }

    #endregion
    
}
